import fs from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { config as loadDotenv, parse as parseEnvFileContents } from "dotenv";
import { updateEnvFileContents, writeEnvFileAtomicallyIfChanged } from "@pilotai/shared/env-file";
import { resolveConfigPath } from "./store.js";

const JWT_SECRET_ENV_KEY = "PILOT_AGENT_JWT_SECRET";
const PILOT_OWNED_ENV_KEY_PATTERN = /^(?:PILOT|PILOT)_[A-Z0-9_]+$/;
function resolveEnvFilePath(configPath?: string) {
  return path.resolve(path.dirname(resolveConfigPath(configPath)), ".env");
}
const loadedEnvFiles = new Set<string>();

function isNonEmpty(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function parseEnvFile(contents: string) {
  try {
    return parseEnvFileContents(contents);
  } catch {
    return {};
  }
}

function emptyEnvFileContents() {
  return [
    "# Pilot environment variables",
    "# Generated by Pilot CLI commands",
    "",
  ].join("\n");
}

function pilotOwnedEntries(entries: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(entries).filter(
      ([key, value]) => PILOT_OWNED_ENV_KEY_PATTERN.test(key) && value.trim().length > 0,
    ),
  );
}

export function resolvePilotEnvFile(configPath?: string): string {
  return resolveEnvFilePath(configPath);
}

export function resolveAgentJwtEnvFile(configPath?: string): string {
  return resolveEnvFilePath(configPath);
}

export function loadPilotEnvFile(configPath?: string): void {
  loadAgentJwtEnvFile(resolveEnvFilePath(configPath));
}

export function loadAgentJwtEnvFile(filePath = resolveEnvFilePath()): void {
  if (loadedEnvFiles.has(filePath)) return;

  if (!fs.existsSync(filePath)) return;
  loadedEnvFiles.add(filePath);
  loadDotenv({ path: filePath, override: false, quiet: true });
}

export function readAgentJwtSecretFromEnv(configPath?: string): string | null {
  loadAgentJwtEnvFile(resolveEnvFilePath(configPath));
  const raw = process.env[JWT_SECRET_ENV_KEY];
  return isNonEmpty(raw) ? raw!.trim() : null;
}

export function readAgentJwtSecretFromEnvFile(filePath = resolveEnvFilePath()): string | null {
  if (!fs.existsSync(filePath)) return null;

  const raw = fs.readFileSync(filePath, "utf-8");
  const values = parseEnvFile(raw);
  const value = values[JWT_SECRET_ENV_KEY];
  return isNonEmpty(value) ? value!.trim() : null;
}

export function ensureAgentJwtSecret(configPath?: string): { secret: string; created: boolean } {
  const existingEnv = readAgentJwtSecretFromEnv(configPath);
  if (existingEnv) {
    return { secret: existingEnv, created: false };
  }

  const envFilePath = resolveEnvFilePath(configPath);
  const existingFile = readAgentJwtSecretFromEnvFile(envFilePath);
  const secret = existingFile ?? randomBytes(32).toString("hex");
  const created = !existingFile;

  if (!existingFile) {
    writeAgentJwtEnv(secret, envFilePath);
  }

  return { secret, created };
}

export function writeAgentJwtEnv(secret: string, filePath = resolveEnvFilePath()): void {
  mergePilotEnvEntries({ [JWT_SECRET_ENV_KEY]: secret }, filePath);
}

export function readPilotEnvEntries(filePath = resolveEnvFilePath()): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  return parseEnvFile(fs.readFileSync(filePath, "utf-8"));
}

export function writePilotEnvEntries(entries: Record<string, string>, filePath = resolveEnvFilePath()): void {
  const previousContents = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  const nextContents = updateEnvFileContents(previousContents ?? emptyEnvFileContents(), pilotOwnedEntries(entries), {
    valueEncoding: "minimal",
  });
  writeEnvFileAtomicallyIfChanged(filePath, previousContents, nextContents);
}

export function mergePilotEnvEntries(
  entries: Record<string, string>,
  filePath = resolveEnvFilePath(),
): Record<string, string> {
  const current = readPilotEnvEntries(filePath);
  const managedEntries = pilotOwnedEntries(entries);
  const next = {
    ...current,
    ...managedEntries,
  };
  writePilotEnvEntries(managedEntries, filePath);
  return next;
}
